
kramdown:
  hard_wrap: true

posts_path: /news
permalink: '/news/:title'

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
    values:
      layout: main
